/*
	Copyright (c) 2019 YottaChain Foundation Ltd. 2015 Christopher A. Taylor.  All rights reserved.

	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are met:

	* Redistributions of source code must retain the above copyright notice,
	  this list of conditions and the following disclaimer.
	* Redistributions in binary form must reproduce the above copyright notice,
	  this list of conditions and the following disclaimer in the documentation
	  and/or other materials provided with the distribution.
	* Neither the name of YTLRC/CM256 nor the names of its contributors may be
	  used to endorse or promote products derived from this software without
	  specific prior written permission.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
	AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
	IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
	ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
	LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
	CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
	SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
	INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
	CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
	ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
	POSSIBILITY OF SUCH DAMAGE.
*/

#ifdef _MSC_VER
    #pragma warning(push)
    #pragma warning(disable: 4530) // warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
#endif

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#ifdef _MSC_VER
    #pragma warning(pop)
#endif


#include "../cm256.h"
#include "../YTLRC.h"

#include <Windows.h>

static double GetPerfFrequencyInverse()
{
    // Static value containing frequency inverse of performance counter
    static double PerfFrequencyInverse = 0.;

    // If not initialized,
    if (PerfFrequencyInverse == 0.)
    {
        // Initialize the inverse (same as in Timer code)
        LARGE_INTEGER freq;
        QueryPerformanceFrequency(&freq);
        PerfFrequencyInverse = 1.0 / (double)freq.QuadPart;
    }

    return PerfFrequencyInverse;
}

void InitializeData(CM256Block originals[256], int dataBlockCount, int totalBlockCount, int blockBytes)
{
    int i, j;
    for (i = 0; i < dataBlockCount; i++) {
        for (j = 0; j < blockBytes; ++j)
            originals[i].pData[j] = (uint8_t)(i + j * 13);
    }
    for (i = dataBlockCount; i < totalBlockCount; i++)
        memset(originals[i].pData, 0, blockBytes);
}

bool ValidateSolution(CM256Block* blocks, int blockCount, int blockBytes)
{
    int i, j;
    uint8_t seen[256] = { 0 };
    bool ret = true;

    for (i = 0; i < blockCount; ++i)
    {
        uint8_t index = blocks[i].lrcIndex;

        if (index >= blockCount)
        {
            return false;
        }

        if (seen[index])
        {
            return false;
        }

        seen[index] = 1;

        for (j = 0; j < blockBytes; ++j)
        {
            const uint8_t expected = (uint8_t)(index + j * 13);
            uint8_t* blockData = (uint8_t*)blocks[i].pData;
            if (blockData[j] != expected)
            {
                printf("[%d, %d]=%d(%d) ", i, j, (int)blockData[j], (int)expected);
                return false;
            }
        }
    }

    return ret;
}


bool ExampleFileUsage()
{
    int i, j;
    if (cm256_init())
    {
        return false;
    }

#ifdef FUTURE
    cm256_encoder_params params;

    // Number of bytes per file block
    params.BlockBytes = 1296;

    // Number of blocks
    params.OriginalCount = 100;

    // Number of additional recovery blocks generated by encoder
    params.RecoveryCount = 30;

    // Size of the original file
    static const int OriginalFileBytes = params.OriginalCount * params.BlockBytes;

    // Allocate and fill the original file data
    uint8_t* originalFileData = new uint8_t[OriginalFileBytes];
    for (i = 0; i < OriginalFileBytes; ++i)
    {
        originalFileData[i] = (uint8_t)i;
    }

    // Pointers to data
    CM256Block blocks[256];
    for (i = 0; i < params.OriginalCount; ++i)
    {
        blocks[i].pData = originalFileData + i * params.BlockBytes;
    }

    // Recovery data
    uint8_t* recoveryBlocks = new uint8_t[params.RecoveryCount * params.BlockBytes];

    // Generate recovery data
    if (cm256_encode(params, blocks, recoveryBlocks))
    {
        return false;
    }

    // Initialize the indices
    for (i = 0; i < params.OriginalCount; ++i)
    {
        blocks[i].Index = cm256_get_original_block_index(&params, i);
    }

    //// Simulate loss of data, substituting a recovery block in its place ////
    for (i = 0; i < params.RecoveryCount && i < params.OriginalCount; ++i)
    {
        blocks[i].pData = recoveryBlocks + params.BlockBytes * i; // First recovery block
        blocks[i].Index = cm256_get_recovery_block_index(&params, i); // First recovery block index
    }
    //// Simulate loss of data, substituting a recovery block in its place ////

    if (cm256_decode(params, blocks))
    {
        return false;
    }

    for (i = 0; i < params.RecoveryCount && i < params.OriginalCount; ++i)
    {
        uint8_t* block = (uint8_t*)blocks[i].pData;
        int index = blocks[i].Index;

        for (j = 0; j < params.BlockBytes; ++j)
        {
            const uint8_t expected = (uint8_t)(j + index * params.BlockBytes);
            if (block[j] != expected)
            {
                return false;
            }
        }
    }

    delete[] originalFileData;
    delete[] recoveryBlocks;
#endif // FUTURE

    return true;
}

bool CheckMemSwap()
{
    int i;
    unsigned char buffa[16 + 8 + 4 + 3];
    memset(buffa, 1, sizeof(buffa));
    unsigned char buffb[16 + 8 + 4 + 3];
    memset(buffb, 2, sizeof(buffb));

    gf256_memswap(buffa, buffb, (int)sizeof(buffa));

    for (i = 0; i < (int)sizeof(buffa); ++i)
    {
        if (buffa[i] != 2)
        {
            return false;
        }
        if (buffb[i] != 1)
        {
            return false;
        }
    }

    gf256_memswap(buffa, buffb, (int)sizeof(buffa));

    for (i = 0; i < (int)sizeof(buffa); ++i)
    {
        if (buffa[i] != 1)
        {
            return false;
        }
        if (buffb[i] != 2)
        {
            return false;
        }
    }

    return true;
}

bool FinerPerfTimingTest()
{
    int i, j;
    SetPriorityClass(GetCurrentProcess(), REALTIME_PRIORITY_CLASS);
    SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL);

    Sleep(1000);

    if (cm256_init())
    {
        return false;
    }

#ifdef  FUTURE // [
    CM256Block blocks[256];

    LARGE_INTEGER tsum;
    tsum.QuadPart = 0;

    cm256_encoder_params params;
    params.BlockBytes = 1296;
    params.OriginalCount = 100;
    params.RecoveryCount = 30;

    unsigned char* orig_data = new unsigned char[256 * params.BlockBytes];
    unsigned char* recoveryData = new unsigned char[256 * params.BlockBytes];

    const int trials = 1000;
    int trial;
    for (trial = 0; trial < trials; ++trial)
    {
        for (i = 0; i < params.BlockBytes * params.OriginalCount; ++i)
        {
            orig_data[i] = (uint8_t)i;
        }

        for (i = 0; i < params.OriginalCount; ++i)
        {
            blocks[i].pData = orig_data + i * params.BlockBytes;
        }

        if (cm256_encode(params, blocks, recoveryData))
        {
            return false;
        }

        // Initialize the indices
        for (i = 0; i < params.OriginalCount; ++i)
        {
            blocks[i].Index = cm256_get_original_block_index(params, i);
        }

        //// Simulate loss of data, substituting a recovery block in its place ////
        for (i = 0; i < params.RecoveryCount && i < params.OriginalCount; ++i)
        {
            blocks[i].pData = recoveryData + params.BlockBytes * i; // First recovery block
            blocks[i].Index = cm256_get_recovery_block_index(&params, i); // First recovery block index
        }
        //// Simulate loss of data, substituting a recovery block in its place ////

        LARGE_INTEGER t0; ::QueryPerformanceCounter(&t0);

        if (cm256_decode(params, blocks))
        {
            return false;
        }

        LARGE_INTEGER t1; ::QueryPerformanceCounter(&t1);
        tsum.QuadPart += t1.QuadPart - t0.QuadPart;

        for (i = 0; i < params.RecoveryCount && i < params.OriginalCount; ++i)
        {
            uint8_t* block = (uint8_t*)blocks[i].pData;
            int index = blocks[i].Index;

            for (j = 0; j < params.BlockBytes; ++j)
            {
                const uint8_t expected = (uint8_t)(j + index * params.BlockBytes);
                if (block[j] != expected)
                {
                    return false;
                }
            }
        }
    }

    double opusec = tsum.QuadPart * GetPerfFrequencyInverse() * 1000000. / trials;
    double mbps = (params.BlockBytes * params.OriginalCount / opusec);

    //cout << opusec << " usec, " << mbps << " MBps" << endl;
    printf("%lf usec, %lf MBps\n", opusec, mbps);

    ::SetThreadPriority(::GetCurrentThread(), THREAD_PRIORITY_NORMAL);
    ::SetPriorityClass(::GetCurrentProcess(), NORMAL_PRIORITY_CLASS);
#endif// ] FUTURE

    return true;
}

bool BulkPerfTesting(int minOriginalCount, int maxOriginalCount, int minRecoveryCount, int maxRecoveryCount)
{
    int i, ii, j;
    if (cm256_init())
    {
        return false;
    }

    static const int MaxBlockBytes = 16 * 1024 / 10 * 10 + 10; // multiple of 10

    uint8_t *orig_data = (uint8_t *)malloc(MAXSHARDS * MaxBlockBytes);

    uint8_t *recoveryData = (uint8_t *)malloc(MAXSHARDS * MaxBlockBytes);

    CM256Block blocks[256];

//    for (blockBytes = 8 * 162; blockBytes <= MaxBlockBytes; blockBytes *= 10)
    int blockBytes = 16 * 1024;
    int originalCount, recoveryCount;
    {
        for (originalCount = minOriginalCount; originalCount <= maxOriginalCount; ++originalCount)
        {
            for (recoveryCount = minRecoveryCount; recoveryCount <= maxRecoveryCount; ++recoveryCount)
            {
                CM256LRC paramLRC;
                paramLRC.BlockBytes = blockBytes;
                paramLRC.OriginalCount = originalCount;
                paramLRC.GlobalRecoveryCount = recoveryCount;
                paramLRC.HorLocalCount = GetHorLocalCount(originalCount);
                paramLRC.VerLocalCount = (originalCount + paramLRC.HorLocalCount - 1) / paramLRC.HorLocalCount;
                paramLRC.TotalOriginalCount = paramLRC.HorLocalCount * paramLRC.VerLocalCount;
                paramLRC.FirstHorRecoveryIndex = 0;
                paramLRC.FirstVerRecoveryIndex = paramLRC.VerLocalCount;
                paramLRC.FirstGlobalRecoveryIndex = paramLRC.VerLocalCount + paramLRC.HorLocalCount;
                paramLRC.LocalRecoveryOfGlobalRecoveryIndex = paramLRC.FirstGlobalRecoveryIndex + paramLRC.GlobalRecoveryCount;
                paramLRC.TotalRecoveryCount = paramLRC.LocalRecoveryOfGlobalRecoveryIndex + 1;

                for (i = 0; i < 256; ++i)
                {
                    blocks[i].pData = orig_data + i * MaxBlockBytes;
                }

                InitializeData(blocks, originalCount, paramLRC.TotalOriginalCount, blockBytes);

                {
                    LARGE_INTEGER t0; QueryPerformanceCounter(&t0);

                    if (cm256_encode(paramLRC, blocks, recoveryData))
                    {
                        printf("Encoder error");
                        return false;
                    }

                    LARGE_INTEGER t1; QueryPerformanceCounter(&t1);

                    LARGE_INTEGER tsum;
                    tsum.QuadPart = t1.QuadPart - t0.QuadPart;
                    double opusec = tsum.QuadPart * GetPerfFrequencyInverse() * 1000000.;
                    double mbps = (paramLRC.BlockBytes * paramLRC.OriginalCount / opusec);

                    //cout << "Encoder: " << blockBytes << " bytes k = " << originalCount << " m = " << recoveryCount << " : " << opusec << " usec, " << mbps << " MBps" << endl;
                    printf("Encoder: %d bytes per block, k = %d, m = %d : %lf usec, %lf MBps\n", blockBytes,  originalCount, recoveryCount, opusec, mbps);
                }

                // Fill in indices
                for (i = 0; i < paramLRC.TotalOriginalCount; ++i)
                {
                    blocks[i].lrcIndex = i;
                    blocks[i].decodeIndex = i;
                }

                /* Test for global recovery */
                for (ii = 0; ii < paramLRC.GlobalRecoveryCount; ++ii)
                {
                    int erasure_index = paramLRC.FirstGlobalRecoveryIndex + ii;
                    blocks[ii].pData = recoveryData + erasure_index * blockBytes;   // Change original blocks to global recovery blocks
                    blocks[ii].decodeIndex = cm256_get_recovery_block_index(&paramLRC, ii+2);
                    blocks[ii].lrcIndex = cm256_get_recovery_block_index(&paramLRC, erasure_index);
                }

                /* Add an additional global recovery block from horizonal local recovery blocks */
                uint8_t horGlobalRecoveryBlock[MaxBlockBytes];

                memcpy(horGlobalRecoveryBlock, recoveryData + paramLRC.FirstHorRecoveryIndex * blockBytes, blockBytes);
                for (i = 1; i < paramLRC.VerLocalCount; i++)
                    gf256_add_mem(horGlobalRecoveryBlock, recoveryData + (paramLRC.FirstHorRecoveryIndex+i) * blockBytes, blockBytes);
                    /*uint8_t *horRecoveryBlock = recoveryData + (paramLRC.FirstHorRecoveryIndex+i) * blockBytes;
                    for (j = 0; j < blockBytes; j++)
                        horGlobalRecoveryBlock[j] ^= horRecoveryBlock[j];
                }*/

                /* Add another additional global recovery block from vertical local recovery blocks */
                uint8_t verGlobalRecoveryBlock[MaxBlockBytes];

                memcpy(verGlobalRecoveryBlock, recoveryData + paramLRC.FirstVerRecoveryIndex * blockBytes, blockBytes);
                for (i = 1; i < paramLRC.HorLocalCount; i++) {
                    gf256_add_mem(verGlobalRecoveryBlock, recoveryData + (paramLRC.FirstVerRecoveryIndex+i) * blockBytes, blockBytes);
                    /*uint8_t *verRecoveryBlock = recoveryData + (paramLRC.FirstVerRecoveryIndex+i) * blockBytes;
                    for (j = 0; j < blockBytes; j++)
                        verGlobalRecoveryBlock[j] ^= verRecoveryBlock[j];*/
                }

                int ii = paramLRC.GlobalRecoveryCount;  // additional global recovery blocks from horizonal local recovery blocks
                blocks[ii].pData = horGlobalRecoveryBlock;
                blocks[ii].decodeIndex = cm256_get_recovery_block_index(&paramLRC, 0);
                blocks[ii].lrcIndex = cm256_get_recovery_block_index(&paramLRC, paramLRC.FirstGlobalRecoveryIndex + paramLRC.GlobalRecoveryCount);

                ii++;  // additional global recovery blocks from horizonal local recovery blocks
                blocks[ii].pData = verGlobalRecoveryBlock;
                blocks[ii].decodeIndex = cm256_get_recovery_block_index(&paramLRC, 1);
                blocks[ii].lrcIndex = cm256_get_recovery_block_index(&paramLRC, paramLRC.FirstGlobalRecoveryIndex + paramLRC.GlobalRecoveryCount + 1);

                {
                    LARGE_INTEGER t0;
                    QueryPerformanceCounter(&t0);

                    cm256_encoder_params params;
                    params.BlockBytes = paramLRC.BlockBytes;
                    params.TotalOriginalCount = paramLRC.TotalOriginalCount;
                    params.FirstElement = 0;
                    params.OriginalCount = paramLRC.OriginalCount;
                    params.RecoveryCount = paramLRC.GlobalRecoveryCount + 2;
                    params.Step = 1;

                    if (cm256_decode(params, blocks))
                    {
                        printf("Decoder error");
                        return false;
                    }

                    LARGE_INTEGER t1; QueryPerformanceCounter(&t1);

                    LARGE_INTEGER tsum;
                    tsum.QuadPart = t1.QuadPart - t0.QuadPart;
                    double opusec = tsum.QuadPart * GetPerfFrequencyInverse() * 1000000.;
                    double mbps = (params.BlockBytes * params.OriginalCount / opusec);

                    //cout << "Decoder: " << blockBytes << " bytes k = " << originalCount << " m = " << recoveryCount << " : " << opusec << " usec, " << mbps << " MBps" << endl;
                    printf("Decoder: %d bytes per block, k = %d, m = %d : %lf usec, %lf MBps\n", blockBytes, originalCount,  recoveryCount, opusec, mbps);
                }

                if (!ValidateSolution(blocks, originalCount, blockBytes))
                {
                    printf("Solution invalid");
                    return false;
                }

                /* Test for local recovery */
                for (ii = 1; ii < paramLRC.HorLocalCount; ++ii)  {  // start from 1 because (0, 0) is reserved for horizonal recovery block
                    int erasure_index = paramLRC.FirstVerRecoveryIndex + ii;
                    blocks[ii].pData = recoveryData + erasure_index * blockBytes;   // Change 1st row of original blocks to vertical recovery blocks except (0, 0)
                    blocks[ii].decodeIndex = cm256_get_recovery_block_index(&paramLRC, 1);   // All vertical recouvery blocks use 2nd encoding matrix
                    blocks[ii].lrcIndex = paramLRC.TotalOriginalCount + erasure_index;
                }
                for (ii = 0; ii < paramLRC.VerLocalCount; ++ii)  {
                    int erasure_index = paramLRC.FirstHorRecoveryIndex + ii;
                    int iBlock = ii * paramLRC.HorLocalCount;
                    blocks[iBlock].pData = recoveryData + erasure_index * blockBytes;   // Change 1st column of original blocks to horizonal recovery blocks
                    blocks[iBlock].decodeIndex = cm256_get_recovery_block_index(&paramLRC, 0);   // All horizonal recouvery blocks use 1st encoding matrix (all ones)
                    blocks[iBlock].lrcIndex = paramLRC.TotalOriginalCount + erasure_index;
                }

                /* Decode vertical columns except 1st one */
                for (ii = 1; ii < paramLRC.HorLocalCount; ii++)  {  // start from 1 because (0, 0) is reserved for horizonal recovery block
                    LARGE_INTEGER t0;
                    QueryPerformanceCounter(&t0);

                    cm256_encoder_params params;
                    params.BlockBytes = paramLRC.BlockBytes;
                    params.TotalOriginalCount = paramLRC.TotalOriginalCount;
                    params.FirstElement = ii;
                    params.OriginalCount = paramLRC.VerLocalCount;
                    params.RecoveryCount = 1;
                    params.Step = paramLRC.HorLocalCount;

                    if (cm256_decode(params, blocks) != 0)
                    {
                        printf("Local vertical %d decoder error", ii);
                        return false;
                    }

                    LARGE_INTEGER t1; QueryPerformanceCounter(&t1);

                    LARGE_INTEGER tsum;
                    tsum.QuadPart = t1.QuadPart - t0.QuadPart;
                    double opusec = tsum.QuadPart * GetPerfFrequencyInverse() * 1000000.;
                    double mbps = (params.BlockBytes * params.OriginalCount / opusec);

                    //printf("Local vertical %d decoder: %d bytes per block, k = %d, m = %d : %lf usec, %lf MBps\n", ii, blockBytes, params.OriginalCount,  params.RecoveryCount, opusec, mbps);
                }

                /* Decode horizonal rows */
                for (ii = 0; ii < paramLRC.VerLocalCount; ii++)  {
                    LARGE_INTEGER t0;
                    QueryPerformanceCounter(&t0);

                    cm256_encoder_params params;
                    params.BlockBytes = paramLRC.BlockBytes;
                    params.TotalOriginalCount = paramLRC.TotalOriginalCount;
                    params.FirstElement = ii * paramLRC.HorLocalCount;
                    params.OriginalCount = paramLRC.HorLocalCount;
                    params.RecoveryCount = 1;
                    params.Step = 1;

                    if (cm256_decode(params, blocks) != 0)
                    {
                        printf("Local horizonal %d decoder error\n", ii);
                        return false;
                    }

                    LARGE_INTEGER t1; QueryPerformanceCounter(&t1);

                    LARGE_INTEGER tsum;
                    tsum.QuadPart = t1.QuadPart - t0.QuadPart;
                    double opusec = tsum.QuadPart * GetPerfFrequencyInverse() * 1000000.;
                    double mbps = (params.BlockBytes * params.OriginalCount / opusec);

                    //printf("Local horizonal %d decoder: %d bytes per block, k = %d, m = %d : %lf usec, %lf MBps\n", ii, blockBytes, params.OriginalCount,  params.RecoveryCount, opusec, mbps);
                }

                if (!ValidateSolution(blocks, originalCount, blockBytes))
                {
                    printf("Solution invalid");
                    return false;
                }
            }
        }
    }

    return true;
}

bool LRCTesting(int minOriginalCount, int maxOriginalCount, int recoveryCount, int numLoops, int shardSize)
{
    int i, ii, j;
    int originalCount;

    if ( minOriginalCount <= 1 || maxOriginalCount >= MAXSHARDS - recoveryCount - 40 )
        return false;
    if ( !LRC_Initial(recoveryCount, 20) )
        return false;

    int MaxBlockBytes = shardSize / 10 * 10 + 10; // multiple of 10

    uint8_t *orig_data = (uint8_t *)malloc(MAXSHARDS * MaxBlockBytes);
    uint8_t *recoveryData = (uint8_t *)malloc(MAXSHARDS * MaxBlockBytes);
    uint8_t *decodedData = (uint8_t *)malloc(MAXSHARDS * MaxBlockBytes);
    uint8_t *shards[MAXSHARDS];
    CM256Block orgBlocks[MAXSHARDS], decodedBlocks[MAXSHARDS];
    for (i = 0; i < maxOriginalCount; i++) {
        shards[i] = orig_data + i * shardSize;
        shards[i][0] = i;   // Index byte
        orgBlocks[i].pData = shards[i] + 1;
        orgBlocks[i].lrcIndex = i;
        orgBlocks[i].decodeIndex = i;
        decodedBlocks[i].pData = decodedData + i * (shardSize - 1);
        decodedBlocks[i].lrcIndex = i;
        decodedBlocks[i].decodeIndex = i;
    }

    for (originalCount = minOriginalCount; originalCount <= maxOriginalCount; originalCount++) {
        LARGE_INTEGER t0, t1, tsum; 
        InitializeData(orgBlocks, originalCount, originalCount, shardSize - 1);

        /* Encode */
        QueryPerformanceCounter(&t0);
        short recoveryCount = LRC_Encode(shards, originalCount, shardSize, recoveryData);
        if ( recoveryCount <= 0) {
            printf("Encoder error\n");
            return false;
        }
        QueryPerformanceCounter(&t1);

        tsum.QuadPart = t1.QuadPart - t0.QuadPart;
        double opusec = tsum.QuadPart * GetPerfFrequencyInverse() * 1000000.;
        double mbps = ((long)(shardSize -1) * originalCount / opusec);
        printf("Encoder: %d bytes per block, k = %d, m = %d : %lf usec, %lf MBps\n", (int)(shardSize-1),  (int)originalCount, (int)recoveryCount, opusec, mbps);
        
        /* Decode */
        for (j = 0; j < numLoops; j++) {
            QueryPerformanceCounter(&t0);
            short hDecode = LRC_BeginDecode(originalCount, shardSize, decodedData);
            if ( hDecode < 0 ) {
                printf("Begin decode error\n");
                return false;
            }
            i = 0;
            uint8_t *pShard;
            do {
                i++;
                ii = (rand() % (originalCount + recoveryCount));
                pShard = ii < originalCount ? orig_data + ii * shardSize : recoveryData + (ii - originalCount) * shardSize;
            } while ( LRC_Decode(hDecode, pShard) <= 0 );
            LRC_FreeHandle(hDecode);
            QueryPerformanceCounter(&t1);

            tsum.QuadPart = t1.QuadPart - t0.QuadPart;
            double opusec = tsum.QuadPart * GetPerfFrequencyInverse() * 1000000.;
            double mbps = ((shardSize - 1) * originalCount / opusec);
            printf("Decoder: %d bytes per block, k = %d, m = %d : %lf usec, %lf MBps\n", (int)(shardSize-1), originalCount, recoveryCount, opusec, mbps);

            if ( !ValidateSolution(decodedBlocks, originalCount, shardSize - 1) ) {
                printf("Solution invalid");
                return false;
            }
        }
    }

    return true;
}

bool RebuildTest(int originalCount, int probability, int recoveryCount, int numLoops, int shardSize)
{
    int i, j, k, iLoop;
    printf("-----Start test LRC_Initial with globalRecoveryCount=34,maxHandles=3 --------\n");
    if ( !LRC_Initial(recoveryCount, 10) ) {
        printf("   LRC_Initial failed\n");
        return false;
    }
    printf("  LRC_Initial ok\n"); 
    printf("----- Start test LRC_BeginRebuild with originalCount=110,iLost=6,shardSize=16384,*pData-------------\n");
    uint8_t * rebuilddata = malloc(shardSize);
    if (NULL == rebuilddata)
        return false;
    uint8_t * shardbuf = malloc(MAXSHARDS * shardSize);
    if (NULL == shardbuf) {
        free (rebuilddata);
        return false;
    }
    uint8_t *shards[MAXSHARDS];
    for (i = 0; i < MAXSHARDS; i++)
        shards[i] = shardbuf + i * shardSize;
    for (iLoop = 0; iLoop < numLoops; ) {
        short iLost = rand() % 256;
        short handle=LRC_BeginRebuild(originalCount, iLost, shardSize, rebuilddata);
        if (handle < 0)
            continue;
        iLoop++;
        printf("\nTest %d: Lost shard %d, rebuild handle = %d\n", iLoop, iLost, handle);

        /* Prepare test data */
        for (i = 0; i < originalCount; i++) {
            shards[i][0] = i;
            for (j = 1; j < shardSize; j++)
                shards[i][j] = rand();
        }
        LRC_Encode(shards, originalCount, shardSize, shardbuf + originalCount * shardSize);

        uint8_t needlist[256];
        short m, n;
        bool bRebuildOK = false;
        while ( !bRebuildOK && (n = LRC_NextRequestList(handle, needlist)) > 0 ) {
            printf("Request %d shards:", n);
            for (i=0; i < n; i++)
                printf("%d ", (int)needlist[i]);
            printf("\n");
            short ret;
            for (i=0;i < n;i++){
                for (m = rand() % n; 0xff == needlist[m]; m = rand() % n);
                /* find a random shard that is not used */
                int index = needlist[m];
                needlist[m] = 0xff; // Mark this shard being used
                if ( n < 100 && (rand() % 100) > probability ) {
                    /* Emulate lost one more shard for locally repairing process */
                    printf("%d is unavailable\n", index);
                    continue;
                }

                ret = LRC_OneShardForRebuild(handle, shards[index]);
                if (ret > 0) {
                    printf("Rebuild Completed ...... ");
                    bRebuildOK = true;
                    break;
                }
                if (ret < 0){
                    printf("add shard %d to rebuilder error \n", index);
                    return false;
                }
            }
        }
        LRC_FreeHandle(handle);
        if (bRebuildOK) {
            if (memcmp(shards[iLost], rebuilddata, shardSize) == 0)
                printf("Verify data OK\n");
            else {
                printf("Rebuild data error\n");
                return false;
            }
        } else {
            printf("Rebuild failed(not enough shards to rebuild)\n");
            return false;
        }
   }
   return true;
}

int main(int argc, const char *argv[])
{
    bool bTest[10] = {false, false, false, false};
    int minOriginalCount = 128;
    int maxOriginalCount = 128;
    int recoveryCount = 12;
    int numLoops = 20;
    int shardSize = 16 * 1024;
    argc -= 3;
    if (argc > 1) {
        int argv1;
        sscanf(argv[1], "%d", &argv1);
        while (argv1 > 0) {
            bTest[argv1 % 10] = true;
            argv1 /= 10;
        }
    }
    if (argc > 2)
        sscanf(argv[2], "%d", &minOriginalCount);
    if (argc > 3)
        sscanf(argv[3], "%d", &maxOriginalCount);
    if (argc > 4)
        sscanf(argv[4], "%d", &recoveryCount);
    if (argc > 5)
        sscanf(argv[5], "%d", &numLoops);
    if (argc > 6)
        sscanf(argv[6], "%d", &shardSize);

    if ( bTest[0] ) {
       if (!ExampleFileUsage())
            return(1);
        if (!CheckMemSwap())
           return(4);
        if (!FinerPerfTimingTest())
            return(2);
    }
    if ( bTest[1] ) {
        if ( !BulkPerfTesting(minOriginalCount, maxOriginalCount, recoveryCount, recoveryCount+2) )
            return 3;
    }
    if ( bTest[2] ) {
        if (!LRCTesting(minOriginalCount, maxOriginalCount, recoveryCount, numLoops, shardSize))
            return(4);
    }
    if ( bTest[3] ) {
        if (!RebuildTest(minOriginalCount, maxOriginalCount, recoveryCount, numLoops, shardSize))
            return(4);
    }

    return 0;
}
